export { copyClipboard } from './copyClipboard'
export { cpfTest } from './cpfTest'
export { getCookie } from './getCookie'
export { getObjectLength } from './getObjectLength'
export { sleep } from './sleep'
export { validGA } from './validGA'
